### ISSUE TITLE
Bug: Thread lock when adding entities to a map

### ISSUE THREAD

**Issue by kirmmin** [NexusForever/NexusForever#157]
**Date:** 23rd May, 2019

**Description:** When a player is logged in and another player logs in to a zone that is not yet instantiated with many entities (like Thayd), the server will lock further processing (sending packets, at least) until all entities were added to the Map being loaded.

**Occurrence:** Always.

**OS:** Windows 10

**Branch/Commit:** "kirmmin/feature-motd" but this branch was based on develop at time of posting

**STR:** 
1. Load up 2 instances of WildStar
2. Log 1 of the instances in to the Housing Skymap (may need to zone there, log out in the housing map, and restart server)
3. Log the other instance in to a second account and enter world.
4. Teleport to Thayd (with entities in database)
5. Try to do a command on the first instance while the other is loading entities - note that no packets return until all entities are added to the Map.

**Observed:** No packets are returned to the first instance until all entities have been added to the map being loaded.

**Expected:** Packet execution should continue and map booting should happen asynchronously without locking all currently available threads.

**Comment by Rawaho** [comment]
This is deliberate and can't be changed without a redesign to the server architecture.
The entire world update is sequential, sessions are first updated (including handling and sending any packets) then all maps are updated asynchronously but the world thread waits for all maps to complete before the next update.

**Comment by kirmmin** [comment]
Gotcha. I assume we'll eventually add some sort of "priming" of maps to prevent locking of the World? This does sound like it may not play nice with instances in the future, though?
Are instances handled differently?

**Comment by Rawaho** [comment]
Entities are already cached by world and grid.

Adding new entities to the world can only be done when a player enters a map since only those that are around the player are actually spawned.

Adding entities should be very quick though, Thyad for me takes only a few MS unless you have logging enabled in which case it takes a few seconds.

**Comment by kirmmin** [comment]
Ah, it's probably the logging :) This was on my dev box, so it had all logs enabled.

All sounds good; I'm pleased it was just my problem and not an issue with the server. I'll close this out. Thanks Rawaho.
