### ISSUE TITLE
Core Change: Rotation when adding to map

### ISSUE THREAD

**Issue by kirmmin** [NexusForever/NexusForever#164]
Currently, `IMap.EnqueueAdd` only accepts an Entity and Position Vector, but no rotation. While this may not be necessary, the rotation values are available in the `WorldLocation2` Table that we use for mapping teleport locations.

`EnqueueAdd`: https://github.com/NexusForever/NexusForever/blob/master/Source/NexusForever.WorldServer/Game/Map/IMap.cs#L10

cc/ @Rawaho

**Comment by Rawaho** [comment]
You just set the rotation value in the entity before calling EnqueueAdd.

**Comment by kirmmin** [comment]
Oh, lol.

This may be the quickest issue we close ;)
