### ISSUE TITLE
Bug: Possibly Borked Character Access with Bag

### ISSUE THREAD

**Issue by aurinjudge** [NexusForever/NexusForever#168]
Title: Possibly Borked Character Access with Bag

Date: 31 May, 2019

Description: Added item #8488 - Quadric Hypersphere (bag) to inventory. Opened Inventory. Dragged bag on top of existing bag (16 or 17 slot, I forget which item #). Immediately disconnected. Attempted to re-log in, stuck on the chompy wheel. Logged in with different account correctly.

Occurrence: Continual on the one account. Will make another account to test repeatability.

OS: Win10 1903 64b

Branch/Commit:

STR: Add bags to slots. 
Add item #8488 - Quadric Hypersphere (bag) to inventory. 
Open Inventory. 
Drag QH bag on top of existing bag
Attempt to re-log in, get stuck on the chompy wheel. 
Log in with different account correctly.

Observed: Chompy wheel.

Expected: Log back in normally

**Comment by kirmmin** [comment]
Was this on my test server, or just running my PR locally?

**Comment by aurinjudge** [comment]
Test server. :D Sorry

**Comment by kirmmin** [comment]
I was able to replicate - taking a look at it now :)

**Comment by aurinjudge** [comment]
Thanks! If it's borked it's borked. I'm literally trying to break things and will happily sacrifice characters and accounts to the Walatiki gods in the name of progress.

**Comment by kirmmin** [comment]
Let me know your character name with the problem and I'll fix it so you can log back in :)

**Comment by aurinjudge** [comment]
Myri Sandglider was the one I was on, I think... I had made about half a dozen. Could also have been Dulannia Gainellius,

**Comment by kirmmin** [comment]
Should be sorted - Bunny Munchkin was the offender :)

**Comment by kirmmin** [comment]
Also, to add, I've got a fix :) Thank you for finding this.

**Comment by aurinjudge** [comment]
Thanks much!
