### ISSUE TITLE
Account

### ISSUE THREAD

**Issue by aurinjudge** [NexusForever/NexusForever#173]
Date: 4 June, 2019

Description: Traveled to RMT to tour, and was in the Bowels of the Ship area, which currently has no exit. Tried an invalid teleport by accident (clearly labeled NOPE NOPE NOPE in the spreadsheet). Intended to !teleport 2161 -0.0378065 2.41675 -9.25301 (the Tideborn Facility), but instead copied/pasted: !teleport 910 48.9703 -921.304 -64.1643 (Timmi's Play Fort). Why? Because I'm a dumbass.

Didn't travel anywhere, but also couldn't travel anywhere else afterwards. Tried to !go Thayd and others. Logged out and exited, relogged and "Your account has a character still in the world. Please try again in a minute." message continues to appear.

Occurrence: Continual.

OS: Win10 1903 64b

Branch/Commit: Kimmrin's TS

STR: 
1) !teleport 3032 -20.1017 600.271 -1046.85
2) !teleport 910 48.9703 -921.304 -64.1643
3) Log out and try to log back in

Observed: Error message above

Expected: Log back in normally

**Comment by kirmmin** [comment]
This is a known issue with the Save process. It can get locked up and not release the account or character, or even re-try the save.
We need to look into fixing this, but it won't be "soon". I can reboot the server, I think you were the only one online, to get you back going.

**Comment by aurinjudge** [comment]
Thanks! :D

**Comment by kirmmin** [comment]
Should be back up now. Thanks for the report.

**Comment by badbaki** [comment]
My PR for a zone blacklist #119 prevents players from teleporting to the nope zones but in the meantime just be careful with the copy pastes ;)

**Comment by aurinjudge** [comment]
I will wear my cone of shame with... humbleness.
