### ISSUE TITLE
[Bug] - [Character Creation]: Name Dupe

### ISSUE THREAD

**Issue by HelperDave** [NexusForever/NexusForever#180]
**TITLE**: 
Naming Dupe

**DATE**: 
10 June 2019

**DESCRIPTION**:
You can currently create a character with a name already taken.

Initially you won't be able to play this character upon creation; (cinematic freeze) however restarting the client will allow you to play the character.

**OCCURRENCE**:
Always

**OS**: 
Win10 - Latest

**BRANCH/COMMIT**:
Develop (latest?) - (Kirmmins)

**STR**: 
Create a character with the same name of another character.

**OBSERVED**:
Initially you won't be able to play this character upon creation; (cinematic freeze) however restarting the client will allow you to play the character.

**EXPECTED**:
Name taken feature implemented.
Certainly to not play the character even if created!

![WildStar 190610 175616](https://user-images.githubusercontent.com/51673399/59211952-18018f00-8ba9-11e9-9a81-a958a5d256e0.png)

**Comment by dyl10s** [comment]
This issue can be closed. @Rawaho
