### ISSUE TITLE
Math error in NexusForever.WorldServer/Game/Entity/CurrencyManager.cs

### ISSUE THREAD

**Issue by myyanf** [NexusForever/NexusForever#190]
This isn't showing up yet as currency caps haven't been set, but it will appear as soon as any are put in place.

In the develop branch, lines 76-78 of NexusForever.WorldServer/Game/Entity/CurrencyManager.cs read:
```
amount += currency.Amount;
if (currency.Entry.CapAmount > 0)
    amount = Math.Min(amount + currency.Amount, currency.Entry.CapAmount);
```
currency.Amount has already been added to amount in line 76, so line 78 should instead read:
```
    amount = Math.Min(amount, currency.Entry.CapAmount);
```
Thanks,
Myya

**Comment by lucas-jones** [comment]
Nice catch 👍
