### ISSUE TITLE
MapGenerator, unable to set patch path or get base map files

### ISSUE THREAD

**Issue by coden1ke** [NexusForever/NexusForever#199]
From the Windows server instructions, I understand that I need to run the Map Generator from the NexusForever.sln. 

I am unable, to missing where I need to define my patch directory for the Wildstar client. 
I have attempted passing the example command with my directory, but it would seem that any parameter passed into the console after the Finished! text is displayed ends the application with exit code 0. 

![image](https://user-images.githubusercontent.com/6880838/63644189-0fe9c380-c6b1-11e9-93fd-f7a9e58f5110.png)

I checked to see if there was a place in a config file where I can define this but was unable to find one.

**Comment by MaxtorCoder** [comment]
What. Don't run it from Visual Studio it self. Run the map extractor from `NexusForever.MapGenerator/bin/Debug/netcoreapp2.2/NexusForever.MapGenerator.dll` and use the parameters listed.

**Comment by coden1ke** [comment]
Understood, Thank you.
