### ISSUE TITLE
MapGenerator executes without instruction parameters

### ISSUE THREAD

**Issue by kirmmin** [NexusForever/NexusForever#203]
**Date:** 22nd September, 2019

**Description:** MapGenerator will execute with no parameters

**Occurrence:** Always

**OS:** Windows 10, Ubuntu 19.04, and Mac OS X 10.14

**Branch/Commit:** develop

**STR:** Execute the application with no parameters. i.e. `dotnet NexusForever.MapGenerator.dll` --i <PatchDir>`

**Observed:** All files are loaded, then the application says Finished, but needs CTRL-C to actually exit.

**Expected:** Errors asking for parameters, maybe?

My output on Windows 10 Powershell:
```
PS C:\Users\Kirmmin\Desktop\NF MapGenerator> dotnet .\NexusForever.MapGenerator.dll -i \\KIRMMIN-IBP\WildStar\Patch     
[INFO][ArchiveManager] Loading archives...
[INFO][MapGenerator] Finished!
```

**Comment by Rawaho** [comment]
Maybe it should show the help output if no other parameters except the input path is supplied?

**Comment by gutmanovaty** [comment]
Istuggled with that also, but up my own server is linux based
The workaround which i used is just to append this parameter ` dotnet run -i ${DIR}/WildStar/Patch/ -g output/ -v`
then simply `cp -a map/ ../NexusForever.WorldServer/ -v` done the work
