### ISSUE TITLE
Bug with Quest Activation Objectives

### ISSUE THREAD

**Issue by crazysheep86** [NexusForever/NexusForever#208]
On the first quest on the Crimson Isle, "Mind the mines, Scrap the Scrab" the mines progress the quest successfully when clicked, however the same mine can be clicked multiple times.

**Comment by Rawaho** [comment]
This is because the spell that is cast when clicking on the mine has a spell effect to despawn it.
We currently don't handle this spell effect so you are able to keep clicking it.
