### ISSUE TITLE
Configurable command aliases

### ISSUE THREAD

**Issue by n30na** [NexusForever/NexusForever#21]
Server-configurable (via config file) command alias system

e.g. to add simple location teleport aliases to simplify testing

**Comment by jasoncouture** [comment]
Should we just load the localized text for zones and link them to the WorldEntries and do it that way? that way you just use the name of the zone.

The official GM command to do this, IIRC, was /c go <zone name>

**Comment by jasoncouture** [comment]
Somthing like /c go Thayd

**Comment by jasoncouture** [comment]
/c go <zone> has been implemented in #46 if this satisfies this issue, please close.
