### ISSUE TITLE
[3 BUGS] First quest : Mines don't explose, but up quest. Impossible to attack Monster. Player with gun don't stop attack 

### ISSUE THREAD

**Issue by Testuff** [NexusForever/NexusForever#220]
Sorry if i'm not in the good channel for help, but impossible to find where i can find help, please.

I'm have 3 BUGS :
- For the first quest, you need to stop some mine. You can click on the mine, but animation for explosion is not "OK", but the quest up good.
- Impossible to attack monster : When i would like to attack a monster, montser don't change color yellow for red, don't lose any life and don't move, exctaly when i don't attack.
- If i choose a player with a gun (TANK), when you use attack with lightning, attack don't stop, we can see a [WARN] for "unsleep" action

If you help me, please

Thank you

**Comment by albeva** [comment]
Questing and combat is not yet implemented. At most what you can do is explore the world and play with housing.

This is still very early stage and has a very long way to go before playable state.

**Comment by MaxtorCoder** [comment]
There is a Discord you can ask this stuff and you would literally get the same answer then.

**Comment by Testuff** [comment]
Thank you, Thank you, for your reply.

I'm on discord but impossible to join de #HELP channel :-(

**Comment by MaxtorCoder** [comment]
How about read the welcome channel man.
