### ISSUE TITLE
Character Tasks

### ISSUE THREAD

**Issue by n30na** [NexusForever/NexusForever#24]
- [x] Inventory
- [x] Creation and appearance saving
- [x] Gear equipping
- [ ] Level and exp
- [ ] LAS editing/remembering
- [ ] Health, focus, and class resources
- [ ] Player attributes
- [ ] Using Mounts
- [ ] Viewing & learning mounts & pets
- [ ] AMPs
- [ ] Bank
- [ ] Gadget & consumables handling
- [ ] Holo-Wardrobe
- [ ] Map Completion tracking
- [ ] Achievement handling
- [ ] Challenge Tracking
- [ ] Primal Matrix
- [ ] Lore collection tracking

**Comment by kirmmin** [comment]
Not sure if I can add extras to this?

- [ ] Path Management
