### ISSUE TITLE
Can't connect to server.

### ISSUE THREAD

**Issue by FelixTECH-io** [NexusForever/NexusForever#242]
**Title:** Can't connect to local test server.

**Date:** 09th December 2019

**Description:** After logging in with the created account the WildStar client says "Connecting to realm NexusForever" and after a few seconds it aborts with a network error (can't connect to server).

**Occurrence:** always

**OS:** Windows 10 Pro Build 1903

**Branch/Commit:** latest release (Travis-881d7a2339a90d30f146ab97ac0f4a187987cab9)

**STR:**
- setup server as in installation guide
- start Auth Server
- start STS Server
- start World Server

**Observed:**
STS Server output after clicking login:
`
[TRACE][Session] New client connected.
[TRACE][Session] Received packet /Sts/Connect.
[TRACE][Session] Received packet /Auth/LoginStart.
[TRACE][Session] Sent packet response 200, OK
[TRACE][Session] Received packet /Auth/KeyData.
[TRACE][Session] Initialised RC4, Key: [ ... some key ... ]
[TRACE][Session] Sent packet response 200, OK
[TRACE][Session] Received packet /Auth/LoginFinish.
[TRACE][Session] Sent packet response 200, OK
[TRACE][Session] Received packet /GameAccount/ListMyAccounts.
[TRACE][Session] Sent packet response 200, OK
[TRACE][Session] Received packet /Auth/RequestGameToken.
[TRACE][Session] Sent packet response 200, OK
[TRACE][Session] Received packet /Sts/Ping.
[TRACE][Session] Received packet /Sts/Ping.
[TRACE][Session] Received packet /Sts/Ping.
[TRACE][Session] Client disconnected.
`
Auth Server output after clicking login:
`
[TRACE][Session] New client connected.
[TRACE][Session] Sent packet ServerHello(0x00000003).
[TRACE][Session] Received packet ClientHelloAuth(0x00000592).
[TRACE][Session] Sent packet ServerAuthAccepted(0x00000591).
[TRACE][Session] Sent packet ServerRealmMessages(0x00000763).
[TRACE][Session] Sent packet ServerRealmInfo(0x000003DB).
[WARN][Session] Received unknown packet 00000000
[TRACE][Session] Client disconnected.
`

**Expected:** login to game

**Comment by BumBum94** [comment]
how did you solve the problem?

**Comment by Rawaho** [comment]
For future reference, if you see "Connecting to realm XXX..." this means the authentication through STS and auth was successful and the client is trying to hand off to the world server.
Make sure your world server is accessible, if you are connecting to a world server that isn't on the local machine you'll need to update the host information in the `server` table in the auth database.
