### ISSUE TITLE
Character creation wrong location

### ISSUE THREAD

**Issue by FelixTECH-io** [NexusForever/NexusForever#246]
**Title:** Character creation wrong location
**Date:** 9th December 2019
**Description:** After creating a new character the initial location on the map is incorrect.
**Occurrence:** always
**OS:** Windows 10 Build 1903
**Branch/Commit:** latest release (Travis-881d7a2339a90d30f146ab97ac0f4a187987cab9)
**STR:** create a new character

**Observed:** initial location is
- x: -7683.81
- y: -942.591
- z: -666.634
- worldId: 870
- worldZoneId: 1227

I haven't found out yet which the correct location is.
My first idea for Aurin:
- x: -770.796
- y: -896.526
- z: -2229.97
- worldId: 990
- worldZoneId: 1417

**Comment by MaxtorCoder** [comment]
This is a known issue already. Remember that this is not a full developed server, there is still much to do. Including player spawns.
