### ISSUE TITLE
Creating Accounts (email) with a capital Letter causes Problems

### ISSUE THREAD

**Issue by mifrgr** [NexusForever/NexusForever#248]
**Title**: Accountname (email) with a capital Letter causes Problems
**Date**: 3rd January 2020
**Description**: If creating a account with a capital first letter, you won't be able to log in; the first letter has to be a small one. On the other Hand, you can login to a created account with a small first letter,it doesn't matter if you write it small or capital.
**Occurrence**: always
**OS**: Windows 7 Ultimate 64 bit
**Branch/Commit**: Latest commit c2ecb9d

**STR**: 
1. Run the server
2. Create Account in the world server console

**Observed**: Log in is not possible, Error Text "invalid email/password is displayed by the game

**Expected**: The server has to distinguish between small or capital letters

**Comment by coding-red-panda** [comment]
Although I'm not an active developer on the project, you should not create entries for emails with capital letters in them, as email addresses should be insensitive to this, and the majority of projects/services always downcase email addresses for this reason.

Workaround : manually change the database entry to use lowercase only for the email

suggestion for NF : always downcase emails when dumping them to the database?

**Comment by kirmmin** [comment]
This is a known issue with the account create method. The username that is sent to the server is converted to lowercase by the client, but we do an exact match on the server. 

There are a couple ways we could fix it, it's just not been a priority for anyone. This'll be a good task for a newer developer to take on :)

Thanks for reporting it.
