### ISSUE TITLE
Social Tasks

### ISSUE THREAD

**Issue by n30na** [NexusForever/NexusForever#25]
- [ ] Chat
- [ ] Friends list
- [ ] Party & raid formation
- [ ] Party chat
- [ ] Housing
- [ ] Guild formation and player list
- [ ] Other basic guild functionality (motd etc)
- [ ] Circles
- [ ] Guild exp/perks
- [ ] Guild bank

**Comment by lucas-jones** [comment]
Say, Yell & Emote chat is done :)
