### ISSUE TITLE
Patch faild - Faild to connect to patch server. (Client)

### ISSUE THREAD

**Issue by Slittis** [NexusForever/NexusForever#252]
Hello,

I am fairly new to all of this and this might be an easy thing i have totaly missed!

But i have gotten all of the servers / databases up and running, but when i come to the connecting part, i get this error message

Patch failed.
Faild to connect to patch server. (a02f0067)
The server name or adress could not be resolved (80072ee7)

i have used the client connector and change the "name" or "ip" to my local one but i just cant get it to work.

Please be kind with your awnsers :)

**Comment by Rawaho** [comment]
It sounds like you are launching the patcher and not the client.
Even if the client can’t connect to the sever you’ll still make it to the login screen.

**Comment by Slittis** [comment]
Strange, should i not use the WildStar64 client after i set the host with the connector ? or am i missing something here? 

Edit
Found the problem, when i chose "en" as lang in the connector it did not work, i changed it to "de" and then it worked, so how do i get it to work on english? i dont get a english ver when i extract from the client, anyone know where i can get the english ver? :)

**Comment by Zaki09** [comment]
@Slittis I also couldn't run WildStar64.exe with language set to en so I downloaded another client from arctium.io and [this](https://www.dropbox.com/s/l3bqq8lscet4fnv/ClientDataEN.zip?dl=0) are the en files that are missing in patch folder. Just put them there. If you get any other issues with the client you can contact me for help :)
