### ISSUE TITLE
Bug: Grid entities unload on a Residence Map

### ISSUE THREAD

**Issue by kirmmin** [NexusForever/NexusForever#258]
**Date:** April 3rd, 2020

**Description:** Plug Entities (Construction Yard) on a Residence Map get removed shortly after entering the map due to the way Grid Unload currently works. 

**Occurrence:** Always

**OS:** Windows 10

**Branch/Commit:** `develop`

**STR:** 
1. Create a new or fresh instance of the `develop` branch.
2. Boot up the server
3. Create a new character and enter world
4. When in world, visit your house `!house teleport`
5. Take note that shortly after entering the Map, the Construction Yard in the center will disappear.

**Observed:** Shortly after entering the Map, the Construction Yard in center will disappear.

**Expected:** All entities on a Residence Map stick around and do not unload.

**Notes:**
I noticed this shortly after the Grid unloading work was done, but forgot to log it. I wrote a small fix that allowed the `ResidenceMap` to not unload unused `Grid` instances, but I'm not sure it's the best way to do it. I'd happily tackle the issue, but unsure of the best way to handle it.

**Comment by Rawaho** [comment]
Should be fixed with new instance changes.
