### ISSUE TITLE
[BUG] teleporting and generic unlock commands causing errors

### ISSUE THREAD

**Issue by Retromissile** [NexusForever/NexusForever#333]
Date: 12/14/2020

Description: Commands are causing errors and don't work. 

Occurrence: Always

OS: Windows 10

Branch/Commit: develop

STR: 

Observed: !house teleport, !teleport location/coordinates and !generic unlockall will cause this error in particular. Didn't check all commands. (!item add **for example** works fine.) No error messages visible on world server, only ingame.

Expected: 

PNG of Bug:

![generic unlockall](https://user-images.githubusercontent.com/45534681/102125461-078b3e00-3e4a-11eb-87b8-6dd2cdb49f8a.png)

**Comment by Matt-Hurd** [comment]
This system has been reworked at some point, can no longer replicate.
