### ISSUE TITLE
[BUG] the first skill of the gunner does not work correctly

### ISSUE THREAD

**Issue by kaorlan** [NexusForever/NexusForever#340]
Title: [BUG] the first skill of the gunner does not work correctly
 
Date:  02/01/2020

Description: the first skill of the gunner does not work correctly, no animation and no damage appearing
Occurrence: Once, sometimes, or always

OS: Windows 10

Branch/Commit: develop

STR: just try to use the skill

Observed: the first skill of the gunner does not work correctly

Expected: i try in exile character

**Comment by MaxtorCoder** [comment]
Spells (damage calculation, learning etc) are currently not working. Some basic spells (without dmg) work.
