### ISSUE TITLE
[BUG] bank connection crash

### ISSUE THREAD

**Issue by kaorlan** [NexusForever/NexusForever#341]
Title: Bank deposit crash connection

Date: 02/01/2020

Description: when I try to deposit an item in the bank the game crashes (error connection)

Occurrence:

OS: windows 10

Branch/Commit: develop
STR: 
1 ; take an item
2: try to deposit and see

Observed: 

Expected:

**Comment by MaxtorCoder** [comment]
As far as I know the Bank isn't implemented correctly?

**Comment by kaorlan** [comment]
no idea, in any case when we put an object in the bank we crash

**Comment by Rawaho** [comment]
Fixed.

**Comment by kaorlan** [comment]
the bug is still present
