### ISSUE TITLE
[BUG] freight forwarder

### ISSUE THREAD

**Issue by kaorlan** [NexusForever/NexusForever#342]
Title: [BUG] freight forwarder

Date: 03/01/2021

Description: when you use the freight forwarder you can no longer cast in skill, mount or access PNJ

Occurrence: always

OS: windows 10

Branch/Commit: develop

STR: 
1. use the freight forwarder
2. try to use skill , mount , etc ...

Observed: 
https://image.noelshack.com/fichiers/2021/53/7/1609695426-ssdddsssddffff.png

Expected:

**Comment by MaxtorCoder** [comment]
Not implemented either, logout should "fix" the casting etc.
