### ISSUE TITLE
.NET Core 5

### ISSUE THREAD

**Issue by naoxnix** [NexusForever/NexusForever#346]
Why was the update to .NET Core 5 done? Will .NET Core 5 be used for the future or will there be more updates? 

.NET Core 3.1 is the LTS version and should therefore be used for stable long term development in my opinion.

**Comment by MaxtorCoder** [comment]
Because .NET 5.0 brings new features and optimizations.

**Comment by Fabi** [comment]
LTS version should only be used in really really critical environments where updating takes time to verify changes or may take too long to update due to breaking changes. Otherwise always update ASAP to newer versions. The advantages are almost always bigger than the disadvantages. Using .NET Core 3.1 instead of NET 5 would be a huge drawback in terms of stability, performance and (language) features

**Comment by naoxnix** [comment]
> LTS version should only be used in really really critical environments where updating takes time to verify changes or may take too long to update due to breaking changes. Otherwise always update ASAP to newer versions. The advantages are almost always bigger than the disadvantages. Using .NET Core 3.1 instead of NET 5 would be a huge drawback in terms of stability, performance and (language) features

What specific stability, performance and features are we talking about here? Has anyone measured or is this just a general assumption?

**Comment by Fabi** [comment]
> > LTS version should only be used in really really critical environments where updating takes time to verify changes or may take too long to update due to breaking changes. Otherwise always update ASAP to newer versions. The advantages are almost always bigger than the disadvantages. Using .NET Core 3.1 instead of NET 5 would be a huge drawback in terms of stability, performance and (language) features
> 
> What specific stability, performance and features are we talking about here? Has anyone measured or is this just a general assumption?

There are .NET blogs available from Microsoft and other people out there. I'm sure you will find them. 

.NET 5 is production ready, faster, smaller, has more features. Like every single discussion about 3.1 vs 5.0 will result in 3.1 being worse in almost all categories.
