### ISSUE TITLE
[Bug] Bank crash

### ISSUE THREAD

**Issue by kaorlan** [NexusForever/NexusForever#353]
date : 09/08/2021 
windows 10 

description ; when I want to put an object in the personal bank, the game crashes and I get this message just by following
![unknown](https://user-images.githubusercontent.com/39433897/128738620-ede7e0e3-a109-43eb-9cda-0a71696024f7.png)

**Comment by MaxtorCoder** [comment]
Please provide a crashlog from the client

**Comment by kaorlan** [comment]
08/09/21 18:05:13 (Info) (Client) cv: 1 1920 1080 59 f:1 0 (0 0) (0 0) (0 0)
08/09/21 18:05:15 (Info) (Client) AMD Ryzen 7 3700X 8-Core Processor              3593 8 24511 v NVIDIA GeForce RTX 2060 SUPER 4095 27.21.14.6677 o a0000 10002 0 3000100 
08/09/21 18:05:15 (Info) (Client) cv: 1 1920 1080 59 f:1 0 (0 0) (0 0) (0 0)
08/09/21 18:05:15 (Info) (Client) vcd: 1 640.000000 1536.000000 1 cd: 64.000000 1  2 t:1 0.000000  1.000000 64 256 2048  1 fx: 1 3  50.000000
08/09/21 18:05:15 (Info) (Gfx) RRR11 a
08/09/21 18:05:15 (Info) (Gfx) reset
08/09/21 18:05:15 (Info) (Client) vcd: 1 1024.000000 1536.000000 1 cd: 64.000000 1  2 t:1 0.000000  1.000000 64 256 2048  1 fx: 1 3  50.000000
08/09/21 18:05:15 (Info) (Client) vcd: 1 1024.000000 2048.000000 1 cd: 64.000000 1  2 t:1 0.000000  1.000000 64 256 2048  1 fx: 1 3  50.000000
08/09/21 18:05:15 (Info) (Client) vcd: 1 1024.000000 2048.000000 1 cd: 64.000000 2  2 t:1 0.000000  1.000000 64 256 2048  1 fx: 1 3  50.000000
08/09/21 18:05:15 (Info) (Client) vcd: 1 1024.000000 2048.000000 1 cd: 64.000000 2  2 t:0 0.000000  1.000000 64 256 2048  1 fx: 1 3  50.000000
08/09/21 18:05:15 (Info) (Client) vcd: 1 1024.000000 2048.000000 1 cd: 64.000000 2  2 t:0 0.000000  1.000000 128 256 2048  1 fx: 1 3  50.000000
08/09/21 18:05:15 (Info) (Client) vcd: 1 1024.000000 2048.000000 1 cd: 64.000000 2  2 t:0 0.000000  1.000000 128 512 2048  1 fx: 1 3  50.000000
08/09/21 18:05:15 (Info) (Client) vcd: 1 1024.000000 2048.000000 1 cd: 64.000000 2  2 t:0 0.000000  1.000000 128 512 4096  1 fx: 1 3  50.000000
08/09/21 18:05:15 (Info) (Gfx) RRR11 b
08/09/21 18:05:15 (Info) (Gfx) lost
08/09/21 18:05:15 (Info) (Gfx) sce3 b npri
08/09/21 18:05:15 (Info) (Gfx) reset
08/09/21 18:05:16 (Info) (Network) NetworkManager Startup
08/09/21 18:05:16 (Warn) (Network) NetworkDriverSelect Startup
08/09/21 18:05:16 (Warn) (Network) NetworkDriverSelect WinSock Startup Version 514: 
08/09/21 18:05:16 (Info) (Auth) Using NCPlatform address [7ff7ddc56f70][0]: 198.245.60.19:6600
08/09/21 18:05:18 (Info) (Gfx) lost
08/09/21 18:05:18 (Info) (Gfx) reset
08/09/21 18:05:44 (Info) (Gfx) lost
08/09/21 18:05:44 (Info) (Gfx) reset
08/09/21 18:05:55 (Info) (Gfx) lost
08/09/21 18:05:55 (Info) (Gfx) reset
08/09/21 18:06:01 (Info) (Gfx) lost
08/09/21 18:06:01 (Info) (Gfx) reset
08/09/21 18:06:11 (Info) (Gfx) lost
08/09/21 18:06:11 (Info) (Gfx) reset
08/09/21 18:06:13 (Info) (Gfx) lost
08/09/21 18:06:13 (Info) (Gfx) reset
08/09/21 18:06:22 (Warn) (Network) SOCKET connect established: (48.2.0.0:2902<->198.245.60.19:23115)
08/09/21 18:06:22 (Warn) (Network) SOCKET connect established: (48.2.0.0:19534<->158.69.245.35:24000)
08/09/21 18:06:24 (Info) (MTX) malformed store banner data: 80072ee7
08/09/21 18:07:30 (Info) (Game) gi 2303d3a0010
08/09/21 18:07:31 (Info) (Game) IC 51 4074.340088 -797.836792 -2399.370117
08/09/21 18:07:31 (Info) (Gfx) lost
08/09/21 18:07:31 (Info) (Gfx) reset
08/09/21 18:07:31 (Info) (Game) acew
08/09/21 18:07:48 (Info) (Gfx) lost
08/09/21 18:07:48 (Info) (Gfx) reset
08/09/21 18:07:48 (Error) (Asset) File not found: UI\Icons\UI_Disconnect_Icon.tex
08/09/21 18:08:22 (Error) (Network) recv(158.69.245.35:24000): error 10053: Unknown success (00002745)

**Comment by kaorlan** [comment]
and in the game i see " lost connection" first

**Comment by kaorlan** [comment]
![Uploading sdfsdfdddddd.png…]()

**Comment by kaorlan** [comment]
![sdfsdfdddddd](https://user-images.githubusercontent.com/39433897/128747261-f14d2fcb-4da5-45aa-9c8e-758a7a9bd81a.png)

**Comment by kaorlan** [comment]
i d'ont have crash log , i think is server side

**Comment by kaorlan** [comment]
ok i made my server and the console tells me that
![dqsdsqdqsdddsss](https://user-images.githubusercontent.com/39433897/129340450-c431e040-28f2-4ade-a68b-a1b7ddfa35dc.png)

**Comment by Rawaho** [comment]
InvalidPacketDataException happens when the server receives an packet value it thinks isn't valid and disconnects the client.
Something might need to change in the packet handler to support this.

**Comment by Matt-Hurd** [comment]
Unable to replicate
