### ISSUE TITLE
[BUG] Spellslingers ability gate does not move your forward

### ISSUE THREAD

**Issue by viktorjac** [NexusForever/NexusForever#402]
Date: 03/01/2022

Description: When using a Cassian spellslinger gate ability the character does not move forward.

Occurrence: Always

OS: Windows 7

Branch/Commit: Test branch

STR:

Cassian Spellslinger
Press ability gate
The animation works but the movement do not happen.

Observed: Spellslinger Cassian

Expected: Move forward 20m and apply stun to foes.

**Comment by MaxtorCoder** [comment]
Please report it on Kirmmin's repository as we don't have Kirmmin's latest changes on the Development branch yet! :)
