### ISSUE TITLE
[Bug] Quest: Waking Elderoot

### ISSUE THREAD

**Issue by nonameform** [NexusForever/NexusForever#403]
The quest won't progress normally, so I used !quest achieve 6302 and got an error.

![image](https://user-images.githubusercontent.com/34381716/150218773-c76a8b43-9c60-47c9-8f81-399f3957eed0.png)

**Comment by MaxtorCoder** [comment]
Report it on Kirmmins's github please. He has an issue page for his test server.

**Comment by nonameform** [comment]
Sorry, my bad.
