### ISSUE TITLE
[BUG] Holo-wardrobe. Impacts wardrobe storage when you hit 350 items.

### ISSUE THREAD

**Issue by Tintookie** [NexusForever/NexusForever#452]
**Date:** 
10/06/2023 Melbourne Australia (I'm sorry, I don't know where you're based so I couldn't work out the time zone difference for you) 
_Time: Roughly 10pm_

**Issue:** 
You're able to unlock the max holo-wardrobe slots to 2350 in game however you can only fill your wardrobe to 350 even though it shows 2350 as the max limit. When you hit 350 items you cannot add anymore items. If you remove items to make room in the wardrobe, doesn't matter the amount but for example say I delete 10 items that are in the wardrobe to make room for 10 new items you're unable to add the new items even though you have space under 350 slots. Logging in and out doesn't work. I did have a few hours gap between gameplay and when I logged back in I was able to add a few more items before it stopped working again. It appears hitting 350 messes the functionality of it. It is not location specific, it happened both on my plot as well as in Thayd. 

I am still able to change costume sets, this just affects the storage side of the wardrobe.

_Character name: Bun Buns / Aurin_
_Location: Thayd_

**Occurrence:** 
Every time once you add 350 pieces to the wardrobe.

**OS:** 
Windows 11 Home / 22H2

_Branch/Commit:  N/A - unsure (using Kirmmin's latest server)_

**STR:**
1. unlock all holo-wardrobe slots via shop. Max is 2350 slots.
2. add items to the wardrobe, reach 350 slots. 
2a. See if you can get past 350 (I could not even though I have unlocked max slots.)
3. Remove items from the wardrobe to drop below 350.
4. Try to add items again to reach or surpass 350.

**Observed:**
Once I hit 350 items I could not add more items to the wardrobe past that number despite having max slots of 2350. When I deleted some items to reduce the number under 350 I then could not add any more items straight after. Hitting 350 locked the ability to add more items regardless of how many spare slots I had.

**Expected:**
1) To keep adding items to my wardrobe to max capacity of 2350.
2) To be able to readd items instantly after deleting items to make space.

**Comment by Rawaho** [comment]
Resolved in commit a19a0dc3efcf4e2c3c667133dfcfadc1c8da3ccb.
Kirmmin and other servers will still need to merge this commit for it to work.
