### ISSUE TITLE
Database Migrations

### ISSUE THREAD

**Issue by jasoncouture** [NexusForever/NexusForever#59]
Database Migrations keeps coming up, So I figured I'd map out a plan and start tackling it.

I plan on doing this in phases, submitting a PR for each step. The idea in doing it this way is to minimize disruption to other developers, and people who may be testing. As well as making it easy to back out changes, should this cause disruptions.

- [x] Abstract configuration to allow different providers (Only MySQL/MariaDB is supported at this time).
- [x] Implement sane design-time loading of configuration.
- [ ] Implement a way to use the current SQL scripts for each database when migrating existing MySQL databases, and insert the appropriate data into the entity framework migration history table. Other DB providers will use migrations only.
- [x] Full conversion of AuthContext, and initial migrations.
- [ ] Full conversion of CharacterContext, and initial migrations.
- [ ] Full conversion of WorldContext, and initial migrations.
- [ ] OPTIONAL: Attempt to implement MSSQL as an alternative.
- [ ] OPTIONAL: Attempt to implement Postgres as an alternative.
- [ ] OPTIONAL: Attempt to Implement SQLite for masochists.

**Comment by MarkWilds** [comment]
Do you need help with this one?

**Comment by jasoncouture** [comment]
@MarkWilds sure, but I am currently waiting for @Rawaho to answer me on a plan. We need to rearrange something in the core to continue.
