### ISSUE TITLE
Account Management

### ISSUE THREAD

**Issue by kirmmin** [NexusForever/NexusForever#83]
- [ ] Account create will create duplicate accounts if the username is the same. (Resolved by #84)
- [ ] Modify password of an account
- [ ] Lock & Ban accounts
- [ ] Account deletion rules? Delete & Ban, Delete & move characters to a different account, Delete all characters, all account stuff.
  - [ ] Account Transaction Logs specifically for creation, deletion, user who did it, and reasoning?
- [ ] Account currencies need to be considered as part of the auth database?
- [ ] Account items, daily rewards, and claimables, as well as any account-related cooldowns, need to be considered as part of the auth database?
- [ ] Holowardrobe needs to be considered as part of the auth database?
- [ ] Account status (User/Dev/GM) not being set anywhere.
- [ ] Account membership (Basic/Signature) not being set anywhere. May not need to be a consideration?

Possibly related to #50

**Comment by jasoncouture** [comment]
I strongly disagree with deleting accounts. Banning them should be enough.

I think everyone should be set to signature (Hardcoded) to discourage "donate and I'll give you sig" behavior. It doesn't stop anyone, but prevents average joe from doing it.

**Comment by kirmmin** [comment]
> I strongly disagree with deleting accounts. Banning them should be enough.
>
I can agree with this. The server currently does delete accounts, and might be something we want for development-mode, but building for release likely wouldn't be necessary.

> I think everyone should be set to signature (Hardcoded) to discourage "donate and I'll give you sig" behavior. It doesn't stop anyone, but prevents average joe from doing it.
>
I also can agree with this, but I added to this issue to aid in discussion of this particular topic. Are we looking to replicate Wildstar at close, or make something very close but with modifications like this?

**Comment by jasoncouture** [comment]
@kirmmin My opinions are my own, but the store should be locked out, or made an in game currency for the reason I speicifed. There's behavior that I never want to see encouraged (Like paid subs on private servers). Being that it's open source, we can't stop it, but if we can discourage it I believe we should. We will never be able to replicate the store as it was, without NCSoft's help, and I don't think this is misaligned with our goals. There will be points like this that we can't replicate at the day of shutdown, if that makes sense.

@Rawaho has final say, obviously, but I feel strongly about this.

**Comment by kirmmin** [comment]
I've built the functionality that works to replicate the store, for the most part. It's just on a dev branch - I haven't had time to work on it further over the past week. I am just missing the purchasing, though it's basically there.
With that said, the store currently requires parses and exporting to work. I could disable (or not merge) the store items in, but we need the store "working" to access things like Account Inventory, Account Titles, etc. I'm all ears - it was still worthwhile coding what I have, at the very least it gives us access to account inventory, etc.

Thank you for the feedback @jasoncouture.
