### ISSUE TITLE
WorldServer: Errors on loading empty .tbl

### ISSUE THREAD

**Issue by codemasher** [NexusForever/NexusForever#87]
Hey, thank you for fixing the dependencies! Auth & Sts are working now, however, the WorldServer errors out on several empty tables. Wildstar Studio shows & exports them as empty and i have no idea if there's any data supposed to be in there.

`[ERROR][GameTableManager] Failed to load CombatReward.tbl in 1,0001ms`

The tables in question are

```
AchievementGroup.tbl
AchievementSubGroup.tbl
Class.tbl
CombatReward.tbl
ComponentRegion.tbl
ComponentRegionRect.tbl
CostumeSpecies.tbl
Creature2Difficulty.tbl
Creature2ModelInfo.tbl
Creature2Resist.tbl
Creature2Tier.tbl
Race.tbl
UnitRace.tbl
Wind.tbl
```

**Comment by Fabi** [comment]
There are 2 different extractors available. You should try them or download the tbl files from https://arctium.ws

**Comment by codemasher** [comment]
Yay that worked! Thank you! Now i have to figure out how to create an acc, start the game and log in ;)
